# Generated by Django 2.2.3 on 2019-07-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.TextField(blank=True, max_length=200, null=True)),
                ('customerPhoneNumber', models.TextField(blank=True, max_length=200, null=True)),
                ('customerRoomNumber', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodName', models.TextField(max_length=200)),
                ('goodKind', models.TextField()),
                ('goodNumberRemain', models.IntegerField(default=100)),
                ('goodInPrice', models.FloatField()),
                ('goodSalePrice', models.FloatField()),
                ('goodPicPath', models.TextField(blank=True, max_length=200, null=True)),
                ('goodTotalSale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.TextField(max_length=200)),
                ('orderCompleted', models.BooleanField(default=False)),
                ('orderTotalPrice', models.FloatField(default=0.0)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smallMarket.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodNumber', models.IntegerField(default=0)),
                ('goodTotalPrice', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smallMarket.Customer')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smallMarket.Good')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smallMarket.Order')),
            ],
        ),
    ]
