# Generated by Django 2.2.3 on 2019-07-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallMarket', '0002_auto_20190708_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordTotalPrice',
            new_name='orderTotalPrice',
        ),
    ]
