# Generated by Django 2.2.3 on 2019-07-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallMarket', '0003_auto_20190708_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='goodTotalPrice',
            field=models.FloatField(default=0),
        ),
    ]
